.base-cargo:
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/.cargo

.base-backend-cache:
  image:
    name: registry.ulbricht.casa/docker-images/rust-docker-base-image:latest
    pull_policy: always
  extends:
    - .base-cargo
  cache:
    key: $CI_PROJECT_NAME-$ARCH-server
    paths:
      - $CI_PROJECT_DIR/target/
      - $CI_PROJECT_DIR/.cargo/
      - $CI_PROJECT_DIR/Cargo.lock

.base-frontend-cache:
  image:
    name: registry.ulbricht.casa/docker-images/leptos-docker-base-image:latest
    pull_policy: always
  extends:
    - .base-cargo
  variables:
    CARGO_PROFILE_RELEASE_PANIC: abort
    CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 1
    CARGO_PROFILE_RELEASE_OPT_LEVEL: z
    CARGO_PROFILE_RELEASE_DEBUG: "false"
    CARGO_PROFILE_RELEASE_LTO: "true"
    CARGO_PROFILE_RELEASE_STRIP: "symbols"
  cache:
    key: $CI_PROJECT_NAME-leptos
    paths:
      - $CI_PROJECT_DIR/pandas-dist/
      - $CI_PROJECT_DIR/groves-dist/
      - $CI_PROJECT_DIR/target/
      - $CI_PROJECT_DIR/.cargo/
      - $CI_PROJECT_DIR/Cargo.lock

.base-docker:
  image:
    name: gcr.io/kaniko-project/executor:debug
    pull_policy: always
    entrypoint: [ "" ]
  before_script:
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"https://index.docker.io/v1/\":{\"auth\":\"$DOCKER_TOKEN\"}}}" > /kaniko/.docker/config.json
  stage: docker
  script:
    - /kaniko/executor -build-arg "APP=$ARCH/bamboo-$APP" --context "dir://${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" $KANIKO_FLAGS
  parallel:
    matrix:
      - APP:
          - mailer
          - events
          - api
          - pandas
          - authentication
        ARCH:
          - amd64
          - arm64

.base-merge-manifests:
  stage: deploy
  image:
    name: mplatform/manifest-tool:alpine
    entrypoint: [ "" ]
  script:
    - >-
      manifest-tool
      --username=${CI_REGISTRY_USER}
      --password=${CI_REGISTRY_PASSWORD}
      push from-args
      --platforms linux/amd64,linux/arm64
      --template ${CI_REGISTRY_IMAGE}/${APP}/ARCH:$TAG
      --target ${CI_REGISTRY_IMAGE}/${APP}:$TAG
  parallel:
    matrix:
      - APP:
          - mailer
          - events
          - api
          - pandas
          - authentication

stages:
  - lint
  - build
  - docker
  - deploy

lint-backend:
  extends:
    - .base-backend-cache
  stage: lint
  script:
    - cargo clippy --release --bin backend-api --bin backend-events --bin backend-mailer

lint-frontend:
  extends:
    - .base-frontend-cache
  stage: lint
  script:
    - cd frontend/$APP
    - cargo clippy --release --features ssr --features hydrate
  parallel:
    matrix:
      - APP:
          - pandas
          - authentication

build-backend:
  extends:
    - .base-backend-cache
  stage: build
  script:
    - cargo build --release --bin backend-api --bin backend-events --bin backend-mailer
    - cp $CI_PROJECT_DIR/target/release/build/bamboo-mailer $ARCH/bamboo-mailer
    - cp $CI_PROJECT_DIR/target/release/build/bamboo-api $ARCH/bamboo-api
    - cp $CI_PROJECT_DIR/target/release/build/bamboo-events $ARCH/bamboo-events
  artifacts:
    paths:
      - $ARCH/bamboo-mailer
      - $ARCH/bamboo-api
      - $ARCH/bamboo-events
  parallel:
    matrix:
      - ARCH:
          - amd64
          - arm64
  tags:
    - runner-${ARCH}

build-frontend:
  extends:
    - .base-frontend-cache
  stage: build
  script:
    - cd frontend/$APP
    - cargo leptos build --release
    - cp $CI_PROJECT_DIR/target/release/build/bamboo-frontend-$APP $ARCH/bamboo-$APP
  artifacts:
    paths:
      - $ARCH/bamboo-$APP
  parallel:
    matrix:
      - APP:
          - pandas
          - authentication
        ARCH:
          - amd64
          - arm64

build-docker-test:
  extends:
    - .base-docker
  stage: docker
  variables:
    KANIKO_FLAGS: --no-push

build-docker-main:
  extends:
    - .base-docker
  stage: docker
  variables:
    KANIKO_FLAGS: --destination "${CI_REGISTRY_IMAGE}/${APP}/${ARCH}:4.0.0-alpha.$CI_PIPELINE_IID"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

build-docker-tag:
  extends:
    - .base-docker
  stage: docker
  variables:
    KANIKO_FLAGS: --destination "${CI_REGISTRY_IMAGE}/${APP}/${ARCH}:$CI_COMMIT_TAG"
  rules:
    - if: $CI_COMMIT_TAG

merge-manifests-tag:
  extends:
    - .base-merge-manifests
  variables:
    TAG: $CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG

merge-manifests-main:
  extends:
    - .base-merge-manifests
  variables:
    TAG: 4.0.0-alpha.$CI_PIPELINE_IID
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

pages:
  image: library/alpine:latest
  stage: deploy
  script:
    - cp -r docs public
    - echo "/* /index.html 200" > public/_redirects
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"