workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME !~ "/^dependabot-.*/"
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

.base-cargo:
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/.cargo

.base-backend-cache:
  image:
    name: registry.ulbricht.casa/docker-images/rust-docker-base-image:latest
    pull_policy: always
  extends:
    - .base-cargo
  cache:
    key: $CI_PROJECT_NAME-$ARCH-server
    paths:
      - $CI_PROJECT_DIR/target/
      - $CI_PROJECT_DIR/.cargo/
      - $CI_PROJECT_DIR/Cargo.lock

.base-frontend-cache:
  image:
    name: registry.ulbricht.casa/docker-images/leptos-docker-base-image:latest
    pull_policy: always
  extends:
    - .base-cargo
  variables:
    CARGO_PROFILE_RELEASE_PANIC: abort
    CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 1
    CARGO_PROFILE_RELEASE_OPT_LEVEL: z
    CARGO_PROFILE_RELEASE_DEBUG: "false"
    CARGO_PROFILE_RELEASE_LTO: "true"
    CARGO_PROFILE_RELEASE_STRIP: "symbols"
  cache:
    key: $CI_PROJECT_NAME-leptos
    paths:
      - $CI_PROJECT_DIR/target/
      - $CI_PROJECT_DIR/.cargo/
      - $CI_PROJECT_DIR/Cargo.lock

.base-docker:
  image:
    name: gcr.io/kaniko-project/executor:debug
    pull_policy: always
    entrypoint: [ "" ]
  before_script:
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"https://index.docker.io/v1/\":{\"auth\":\"$DOCKER_TOKEN\"}}}" > /kaniko/.docker/config.json
  stage: docker
  script:
    - /kaniko/executor --build-arg "APP=$ARCH/bamboo-$APP" --context "dir://${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" $KANIKO_FLAGS
  parallel:
    matrix:
      - APP:
          - mailer
          - events
          - api
          - pandas
          - authentication
          - migrator
        ARCH:
          - amd64
          - arm64

.base-merge-manifests:
  stage: deploy
  image:
    name: mplatform/manifest-tool:alpine
    entrypoint: [ "" ]
  script:
    - >-
      manifest-tool
      --username=${CI_REGISTRY_USER}
      --password=${CI_REGISTRY_PASSWORD}
      push from-args
      --platforms linux/amd64,linux/arm64
      --template ${CI_REGISTRY_IMAGE}/${APP}/ARCH:$TAG
      --target ${CI_REGISTRY_IMAGE}/${APP}:$TAG
  parallel:
    matrix:
      - APP:
          - mailer
          - events
          - api
          - pandas
          - authentication
          - migrator

.base-review:
  image:
    name: registry.ulbricht.casa/docker-images/kubectl:latest
    entrypoint: [ '' ]
  stage: deploy-testing
  tags:
    - kube

stages:
  - lint
  - build
  - docker
  - deploy
  - deploy-testing

lint-backend:
  extends:
    - .base-backend-cache
  stage: lint
  script:
    - cargo clippy --release --bin bamboo-api --bin bamboo-events --bin bamboo-mailer --bin bamboo-migrator

lint-frontend:
  extends:
    - .base-frontend-cache
  stage: lint
  script:
    - cd frontend/$APP
    - cargo clippy --release --features ssr --features hydrate
  parallel:
    matrix:
      - APP:
          - pandas
          - authentication

build-backend:
  extends:
    - .base-backend-cache
  stage: build
  script:
    - cargo build --release --bin bamboo-api --bin bamboo-events --bin bamboo-mailer --bin bamboo-migrator
    - mkdir -p $CI_PROJECT_DIR/$ARCH
    - cp $CI_PROJECT_DIR/target/release/bamboo-mailer $CI_PROJECT_DIR/$ARCH/bamboo-mailer
    - cp $CI_PROJECT_DIR/target/release/bamboo-api $CI_PROJECT_DIR/$ARCH/bamboo-api
    - cp $CI_PROJECT_DIR/target/release/bamboo-events $CI_PROJECT_DIR/$ARCH/bamboo-events
    - cp $CI_PROJECT_DIR/target/release/bamboo-migrator $CI_PROJECT_DIR/$ARCH/bamboo-migrator
  artifacts:
    paths:
      - $ARCH/bamboo-mailer
      - $ARCH/bamboo-api
      - $ARCH/bamboo-events
      - $ARCH/bamboo-migrator
  parallel:
    matrix:
      - ARCH:
          - amd64
          - arm64
  tags:
    - runner-${ARCH}

build-frontend:
  extends:
    - .base-frontend-cache
  stage: build
  script:
    - cd frontend/$APP
    - cargo leptos build --release
    - mkdir -p $CI_PROJECT_DIR/$ARCH
    - cp $CI_PROJECT_DIR/target/release/bamboo-frontend-$APP $CI_PROJECT_DIR/$ARCH/bamboo-$APP
  artifacts:
    paths:
      - $CI_PROJECT_DIR/$ARCH/bamboo-$APP
  parallel:
    matrix:
      - APP:
          - pandas
          - authentication
        ARCH:
          - amd64
          - arm64

build-docker-test:
  extends:
    - .base-docker
  stage: docker
  variables:
    KANIKO_FLAGS: --no-push

build-docker-mr:
  extends:
    - .base-docker
  stage: docker
  variables:
    KANIKO_FLAGS: --destination ${CI_REGISTRY_IMAGE}/${APP}/${ARCH}:4.0.0-alpha.${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}.${CI_PIPELINE_IID}
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

build-docker-main:
  extends:
    - .base-docker
  stage: docker
  variables:
    KANIKO_FLAGS: --destination "${CI_REGISTRY_IMAGE}/${APP}/${ARCH}:4.0.0-beta.$CI_PIPELINE_IID"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

build-docker-tag:
  extends:
    - .base-docker
  stage: docker
  variables:
    KANIKO_FLAGS: --destination "${CI_REGISTRY_IMAGE}/${APP}/${ARCH}:$CI_COMMIT_TAG"
  rules:
    - if: $CI_COMMIT_TAG

merge-manifests-tag:
  extends:
    - .base-merge-manifests
  variables:
    TAG: $CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG

merge-manifests-mr:
  extends:
    - .base-merge-manifests
  variables:
    TAG: $CI_COMMIT_TAG
  script:
    - >-
      manifest-tool
      --username=${CI_REGISTRY_USER}
      --password=${CI_REGISTRY_PASSWORD}
      push from-args
      --platforms linux/amd64,linux/arm64
      --template ${CI_REGISTRY_IMAGE}/${APP}/ARCH:4.0.0-alpha.${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}.${CI_PIPELINE_IID}
      --target ${CI_REGISTRY_IMAGE}/${APP}:4.0.0-alpha.${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}.${CI_PIPELINE_IID}
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

merge-manifests-main:
  extends:
    - .base-merge-manifests
  variables:
    TAG: 4.0.0-beta.$CI_PIPELINE_IID
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

deploy-review:
  extends:
    - .base-review
  script:
    # Prepare the manifest
    - export BRANCH=`echo "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" | awk '{print tolower($0)}'`
    - export TAG="4\\.0\\.0-alpha\\.$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME\\.$CI_PIPELINE_IID"
    - cd $CI_PROJECT_DIR/kubernetes/kustomize/review/
    - echo $MAILER_PASSWORD > secrets/MAILER_PASSWORD
    - echo $S3_ACCESS_KEY > secrets/S3_ACCESS_KEY
    - echo $S3_SECRET_KEY > secrets/S3_SECRET_KEY
    - kubectl kustomize > manifest.yaml
    - sed -i "s/\$BRANCH/$BRANCH/g" manifest.yaml
    - sed -i "s/\$TAG/$TAG/g" manifest.yaml
    # Create the namespace and apply the manifest
    - kubectl create namespace bamboo-review-$BRANCH --dry-run=client -o yaml | kubectl apply -f -
    - kubectl apply -n bamboo-review-$BRANCH -f manifest.yaml
    # Wait for the postgres container to be ready
    - sleep 30
    - kubectl wait --for=condition=Ready -n bamboo-review-$BRANCH pods -l bambushain.app/app=postgres --timeout=90s
    # Synchronize the production database to the local test database
    - sed -i "s/\$POSTGRES_PANDAS/$LIVE_DATABASE/g" sync-database.yaml
    - sed -i "s/\$BRANCH/$BRANCH/g" sync-database.yaml
    - kubectl apply -n bamboo-review-$BRANCH -f sync-database.yaml
    # Wait for the database to be synchronized
    - sleep 30
    - kubectl wait --for=condition=complete job/sync-database -n bamboo-review-$BRANCH --timeout=90s
    # Migrate the database to the current development version
    - sed -i "s/\$TAG/$TAG/g" migrate.yaml
    - kubectl apply -n bamboo-review-$BRANCH -f migrate.yaml
    # Wait for the database to be migrated
    - sleep 30
    - kubectl wait --for=condition=complete job/migrate-database -n bamboo-review-$BRANCH --timeout=90s
    - "curl -H 'Content-Type: application/json' -X POST -d '{\"content\":\"Hey @BambushainTeam, eine neue Testversion ist online. Ihr könnt sie unter https://$CI_ENVIRONMENT_SLUG-review.bambushain.app erreichen.\"}' $DISCORD_WEBHOOK"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG-review.bambushain.app
    on_stop: stop-review
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

stop-review:
  image:
    name: bitnami/kubectl:latest
    entrypoint: [ '' ]
  stage: deploy-testing
  script:
    - kubectl delete namespace bamboo-review-${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME,,}
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual

pages:
  image: library/alpine:latest
  stage: deploy
  script:
    - cp -r docs public
    - echo "/* /index.html 200" > public/_redirects
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"