workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME !~ "/^dependabot-.*/"
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

include:
  - /ci/gitlab/api-docs.yml
  - /ci/gitlab/backend.yml
  - /ci/gitlab/base.yml
  - /ci/gitlab/container.yml
  - /ci/gitlab/frontend.yml
  - /ci/gitlab/review.yml
  - /ci/gitlab/stages.yml