apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bamboo
  namespace: {{ include "bambushain.namespace" . }}
  labels:
    {{- include "bambushain.labels" . | nindent 4 }}
spec:
  rules:
    - host: "{{ .Values.branch }}-review.bambushain.app"
      http:
        paths:
          - backend:
              service:
                name: bamboo-api
                port:
                  name: api
            pathType: Prefix
            path: /api
    - host: "{{ .Values.branch }}-review.bambushain.app"
      http:
        paths:
          - backend:
              service:
                name: bamboo-authentication
                port:
                  name: authentication
            pathType: Prefix
            path: /authentication
    - host: "{{ .Values.branch }}-review.bambushain.app"
      http:
        paths:
          - backend:
              service:
                name: bamboo-pandas
                port:
                  name: pandas
            pathType: Prefix
            path: /pandas
    - host: "{{ .Values.branch }}-review.bambushain.app"
      http:
        paths:
          - backend:
              service:
                name: bamboo-public
                port:
                  name: public
            pathType: Prefix
            path: /
    - host: "{{ .Values.branch }}-review.bambushain.app"
      http:
        paths:
          - backend:
              service:
                name: bamboo-sse
                port:
                  name: sse
            pathType: Prefix
            path: /sse