apiVersion: v1
kind: Secret
metadata:
  name: bamboo
  namespace: {{ include "bambushain.namespace" . }}
  labels:
    {{- include "bambushain.labels" . | nindent 4 }}
stringData:
  DATABASE_URL: {{ .Values.bamboo.config.databaseUrl | quote }}
  MAILER_ENCRYPTION: {{ .Values.bamboo.config.mailer.encryption | quote }}
  MAILER_FROM: {{ .Values.bamboo.config.mailer.from | quote }}
  MAILER_PORT: {{ .Values.bamboo.config.mailer.port | quote }}
  MAILER_SERVER: {{ .Values.bamboo.config.mailer.server | quote }}
  MAILER_STARTTLS: {{ .Values.bamboo.config.mailer.starttls | quote }}
  MAILER_USERNAME: {{ .Values.bamboo.config.mailer.username | quote }}
  NATS_SERVER: {{ .Values.bamboo.config.natsServer | quote }}
  RUST_LOG: {{ .Values.bamboo.config.rustLog | quote }}
  S3_BUCKET: {{ .Values.bamboo.config.s3.bucket | quote }}
  S3_ENDPOINT: {{ .Values.bamboo.config.s3.endpoint | quote }}
  S3_REGION: {{ .Values.bamboo.config.s3.region | quote }}
  S3_USE_PATH_STYLE: {{ .Values.bamboo.config.s3.usePathStyle | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: passwords
  namespace: {{ include "bambushain.namespace" . }}
  labels:
    {{- include "bambushain.labels" . | nindent 4 }}
stringData:
  MAILER_PASSWORD: {{ .Values.bamboo.config.mailer.password | quote }}
  S3_ACCESS_KEY: {{ .Values.bamboo.config.s3.accessKey | quote }}
  S3_SECRET_KEY: {{ .Values.bamboo.config.s3.secretKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: fcm-service-account
  namespace: {{ include "bambushain.namespace" . }}
  labels:
    {{- include "bambushain.labels" . | nindent 4 }}
data:
  fcm-service-account.json: {{ tpl (.Files.Get .Values.bamboo.config.firebase.serviceAccount) . | b64enc | quote }}