apiVersion: v1
kind: Service
metadata:
  name: bamboo
  namespace: {{ include "bambushain.namespace" . }}
  labels:
    {{- include "bambushain.labels" . | nindent 4 }}
spec:
  selector:
    bambushain.app/app: bamboo
  ports:
    - protocol: TCP
      port: 4010
      name: api
    - protocol: TCP
      port: 4020
      name: events
    - protocol: TCP
      port: 4070
      name: public
    - protocol: TCP
      port: 4080
      name: pandas
    - protocol: TCP
      port: 4090
      name: authentication