apiVersion: apps/v1
kind: Deployment
metadata:
  name: bamboo
  namespace: {{ include "bambushain.namespace" . }}
  labels:
    {{- include "bambushain.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      bambushain.app/app: bamboo
  replicas: {{ .Values.bamboo.replicas }}
  template:
    metadata:
      labels:
        bambushain.app/app: bamboo
        {{- include "bambushain.labels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.registry }}/{{ .Values.bamboo.image.api }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: bamboo
            - secretRef:
                name: passwords
          ports:
            - containerPort: 4010
        - name: authentication
          image: "{{ .Values.image.registry }}/{{ .Values.bamboo.image.authentication }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: bamboo
            - secretRef:
                name: passwords
          env:
            - name: LEPTOS_SITE_ADDR
              value: 0.0.0.0:4090
          ports:
            - containerPort: 4090
        - name: events
          image: "{{ .Values.image.registry }}/{{ .Values.bamboo.image.sse }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: bamboo
            - secretRef:
                name: passwords
          ports:
            - containerPort: 4020
        - name: mailer
          image: "{{ .Values.image.registry }}/{{ .Values.bamboo.image.mailer }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: bamboo
            - secretRef:
                name: passwords
        - name: mailer-notifications
          image: "{{ .Values.image.registry }}/{{ .Values.bamboo.image.mailerNotifications }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: bamboo
            - secretRef:
                name: passwords
        - name: pandas
          image: "{{ .Values.image.registry }}/{{ .Values.bamboo.image.pandas }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: bamboo
            - secretRef:
                name: passwords
          env:
            - name: LEPTOS_SITE_ADDR
              value: 0.0.0.0:4080
          ports:
            - containerPort: 4080
        - name: public
          image: "{{ .Values.image.registry }}/{{ .Values.bamboo.image.public }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: bamboo
            - secretRef:
                name: passwords
          env:
            - name: STATIC_DIR
              value: /public/assets
          ports:
            - containerPort: 4070
        - name: reminder
          image: "{{ .Values.image.registry }}/{{ .Values.bamboo.image.reminder }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: bamboo
            - secretRef:
                name: passwords
