{{- if .Values.postgres.sync.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-sync-commands
  namespace: {{ include "bambushain.namespace" . }}
  labels:
    {{- include "bambushain.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
data:
  dump-live.sh: |
    #!/usr/bin/env sh
    pg_dump {{ .Values.postgres.sync.liveDatabase.database }} > /data/{{ .Values.postgres.sync.liveDatabase.database }}.sql

    sed 's/{{ .Values.postgres.sync.liveDatabase.database }}/bamboo/g' /data/{{ .Values.postgres.sync.liveDatabase.database }}.sql > /data/bamboo.sql    
    sed -i 's/ALTER SCHEMA public OWNER TO postgres/ALTER SCHEMA public OWNER TO bamboo/g' /data/bamboo.sql
    echo 'ALTER ROLE bamboo SET search_path TO public;' >> /data/bamboo.sql
    echo 'UPDATE authentication."user" SET totp_validated = false, totp_secret = null, totp_secret_encrypted = true;' >> /data/bamboo.sql
  sync-database.sh: |
    #!/usr/bin/env sh
    psql --file=/scripts/clear-database.sql --echo-error bamboo
    psql --file=/data/bamboo.sql --echo-error bamboo
  clear-database.sql: |
    DROP SCHEMA IF EXISTS authentication CASCADE;
    DROP SCHEMA IF EXISTS bamboo CASCADE;
    DROP SCHEMA IF EXISTS final_fantasy CASCADE;
    DROP SCHEMA IF EXISTS grove CASCADE;
    DROP TABLE IF EXISTS public.seaql_migrations CASCADE;
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sync-database
  namespace: {{ include "bambushain.namespace" . }}
  labels:
    {{- include "bambushain.labels" . | nindent 4 }}
spec:
  parallelism: 1
  template:
    metadata:
      labels:
        {{- include "bambushain.labels" . | nindent 8 }}
    spec:
      initContainers:
        - name: export-database
          image: library/postgres:17
          imagePullPolicy: IfNotPresent
          env:
            - name: PGHOST
              value: {{ .Values.postgres.sync.liveDatabase.host }}
            - name: PGPASSWORD
              value: {{ .Values.postgres.sync.liveDatabase.password }}
            - name: PGUSER
              value: {{ .Values.postgres.sync.liveDatabase.user }}
          command:
            - /bin/sh
            - -c
            - /scripts/dump-live.sh
          volumeMounts:
            - mountPath: /scripts
              name: scripts
            - mountPath: /data
              name: data
      containers:
        - name: sync-testsystem
          image: library/postgres:17
          imagePullPolicy: IfNotPresent
          env:
            - name: PGHOST
              value: postgres
            - name: PGPASSWORD
              value: bamboo
            - name: PGUSER
              value: bamboo
          command:
            - /bin/sh
            - -c
            - /scripts/sync-database.sh
          volumeMounts:
            - mountPath: /scripts
              name: scripts
            - mountPath: /data
              name: data
      volumes:
        - name: scripts
          configMap:
            name: database-sync-commands
            defaultMode: 0777
        - name: data
          emptyDir: { }
      restartPolicy: Never
{{- end }}