namespace: bamboo-review-$BRANCH

resources:
  - nats
  - bamboo
  - postgres

labels:
  - pairs:
      bambushain.app/branch: $BRANCH
    includeSelectors: true
    includeTemplates: true

secretGenerator:
  - name: passwords
    files:
      - secrets/MAILER_PASSWORD
      - secrets/S3_ACCESS_KEY
      - secrets/S3_SECRET_KEY